language: ruby
rvm:
- 2.6.1
before_install:
- gem install bundler
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: SaUEFbyfYJc3gZNogbP9Dn/6WrgqeHkQ/a0owwRrANSUGDXyfkVFw4JmHqV5SSw+qd7hfFusGJ1wxw9x62NpXdcXrO8GXbwj5bj1TdFcQr6fJOTJBhurlml5u2WU3P9/4ubgMTUkXt1rvkvurfe4wzDNQOi8eHIFFzAHLq2gG1F2YbRnlVefIoXmHS0MpO3fAFmVdRMMHyazW5O0A2rn8jwuF6D+PYi4AEhjPuxpb171AwWTw0jfCKWL4TNkGRPeSuSKgTzyPF3DJ+ykCfgAkvmqHdkgPd3qvW4pTqsUS1BIw/SzQFBz1wtgJ6aLESkmKTFp7kZPWTz3ALOGk1dWPKiLxI3wvGr62u7J+Lm0tnEjip0kimKoeBc9Bs8stLWx9iq9olj213+aBTfdeEBGSrqtsdOD+S0psnIt3kqhlk/uT29R7i5P+Xdr7jZlrXvoA+nCiIE0XTERbXr5Tan6kuuy0knMLZFuoc2YUT3d5pSOCIy/uWSe6VVxNKXpcsrcTQvYu0JnlDWh86kXiPTF5fX/CBi3YiIMyMuqfGmRYxgVr73aT0f7c5deHkvrc3t2JCMSr3dtIG0TaFCrypwjH/nj2kkgTWV11iIib+KbF3y9UzwKR4amgkx0emcQKISEv+91W7pMOVNCFW27xpPZtYhm7hTvwBBM6b8+zSL3tvY=
  app: vol-4-alpaca
  on:
    repo: netguru-code-college/vol4-alpaca
env:
  secure: kvBI6Rfotjahj24NBk+FEoxSY7qmZeXy0TA3/WAKNSxJybEdhjQFw0lN6NGrbj7I63dvvUJHzrwABAs1Q5ez3z5rJQ0yssekxoA+Y++qgEJ/CnP2fUb/QdrI+yLqpaSJV0SG9pXSxJj/VoosrY8M8LBwnG/I/3D9RYy3vtyZbCUMJ6xT89EkPe8tpKJViDRa3TOiGx8e9JBR/Fo7/VeUlz22O2yFsXPm9HDzpe3KsyI3oLB0tQzbKGgbdx1L1ru6OA06NPXoJD1K9cVK5SAfz5IWu2ne1d0DTZarVjGmtTaKAMJSBEWtw6bB8eYT8BQLHfIVMyCIe8ofCkXpsJmZa9jNa39rhXEh0LkwGhqIp/Kufyc/rSVVMvF0anfn5h+NWtBb+l7cfk+fbDL2vLPz02wQiI72F8SxJSzW2zUYblsmyhQoBg5sBbq5xPChCvVeN3p1tq/NLkLEYVVGYdxMO4tvM48IoSaFMIEvd/c7j8NkeAo3Cbr9iHhjkFrBDUrGSIm37p8usDeng/VNeRNStHYlnfDssQ8HKC/lNUeLLONvykrqWdw4PuEWsNUhA+ccNm0A0IgRIRuCI7ZFS5d5V1I3b6/qN7tsVkn41pW9VP2Mm1Brie1QoTLkbQ6vPwPY6GxNlHUaJUMj+RK5p+vhf4/uZrjKHZwt5V/Uq1G0Wgo=
